---

#install docker 

- name: Update apt cache 
  become: true
  apt:
    upgrade: "yes"
    update_cache: yes
    cache_valid_time: 86400 #Oneday


- name: Upgrade all apt packages
  apt:
    upgrade: dist

- name: Install dependencies
  apt:
    name: "{{ docker_required_packages }}"
    state: present
    update_cache: yes

- name: Add Docker GPG apt Key
  apt_key:
    url:  "{{ docker_gpg_url }}"
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present

- name: install a docker
  apt:
    name: "{{ docker_packges }}"
    state: latest
    update_cache: yes
- name: Install Python Docker module
  pip:
    name: docker

- name: Add adminstrator to docker group
  user:
    name: "{{ admin_user }}"
    groups: docker
    append: yes



- name: Install Docker Compose
  get_url:
    url: "{{ docker_compose_url }}"
    dest: /usr/local/bin/docker-compose
    mode: u+x,g+x,o+x

- name: assicurati che docker sia attivo
  service:
    name: docker
    state: started
    enabled: yes
